### ISSUE TITLE
Unity - Missing safety steps for license keys

### ISSUE THREAD

**Issue by reyalpsirc** [MARUI-PlugIn/MiVRy#1]
The current documentation steps regarding on how to activate the license will cause a leak of the license id and key on git repositories:

![image](https://user-images.githubusercontent.com/5243311/208128536-6350e380-5695-4b4a-9e14-93facd154fa0.png)

The documentation should give steps to prevent this so that keys are not leaked in git.

## Workaround

In order to bypass this problem, I used a .env file on my Unity project using [CandyCoded/env](https://github.com/CandyCoded/env).

After installing the library above, I created a **.env** with the keys:

	MYVRY_LICENSE_ID="<my_license_id>"
	MIVRY_LICENSE_KEY="<my_license_key>"

Replace `<my_license_id>` and `<my_license_key>` by the real values and then add this to the **.gitignore** file at the root of your repository:

	# Ignore .env files from the repository
	.env

Finally, create a C# file, attach it to all objects containing `GestureManager` or `Mivry` scripts and set its content to this:

	using System;
	using System.Collections;
	using System.Collections.Generic;
	using CandyCoded.env;
	using UnityEngine;

	public class MivrySetupLicense : MonoBehaviour
	{
	    // Start is called before the first frame update
	    void Awake()
	    {
	        GestureManager gestureManager = FindObjectOfType<GestureManager>();
	        if (gestureManager != null) {
	            gestureManager.license_id = env.variables.ContainsKey("MYVRY_LICENSE_ID") ? env.variables["MYVRY_LICENSE_ID"] : "";
	            gestureManager.license_key = env.variables.ContainsKey("MIVRY_LICENSE_KEY") ? env.variables["MIVRY_LICENSE_KEY"] : "";
	            // triggers a refresh of the key
	            int numberOfParts = gestureManager.numberOfParts;
	            gestureManager.numberOfParts = -1;
	            gestureManager.numberOfParts = numberOfParts; 
	            
	        }
	        Mivry myvry = FindObjectOfType<Mivry>();
	        if (myvry != null) {
	            myvry.LicenseName = env.variables.ContainsKey("MYVRY_LICENSE_ID") ? env.variables["MYVRY_LICENSE_ID"] : "";
	            myvry.LicenseKey = env.variables.ContainsKey("MIVRY_LICENSE_KEY") ? env.variables["MIVRY_LICENSE_KEY"] : "";
	        }
	    }
	}

**Comment by max-krichenbauer** [comment]
Thank you!
I'll add the workaround in the next version update.

**Comment by max-krichenbauer** [comment]
Version v2.7 now supports saving the license information in a file which may be hidden:
https://www.marui-plugin.com/documentation-mivry/#license
