### ISSUE TITLE
Support 2D gestures in 3D environment

### ISSUE THREAD

**Issue by reyalpsirc** [MARUI-PlugIn/MiVRy#2]
Is it possible to use Mivry to record and identify gestures in VR that are drawn in a small whiteboard/plane in VR?

The idea is that the player draws the gesture on a fixed plane and then we feed the drawn pixels as the gesture to be identified/recorded by Mivry.

Is it possible by creating our own recorder and feeding the points as a Vector3 where Z is always zero? If so, are there any guidelines on how we can achieve that?

**Comment by max-krichenbauer** [comment]
Hello!

Mivry works with 2D gestures just as well as with 3D gestures.

However, unlike OCR, the direction of the motion is required, and it must be one continuous motion per gesture.
So feeding it a pixel image of (potentially) multiple strokes without any knowledge of the order and direction in which the strokes were painted will be difficult.

It is more advisable to feed the motion of the hand (or tip of the pen) drawing on the whiteboard into MiVRy as Vector3.
You can either use x/y coordinate on the whiteboard and set z=0,
or you can use the global position (x, y, z), and use the whiteboards position and rotation as "head" position and rotation - then MiVRy will perform the coordinate system transformation internally.

**Comment by reyalpsirc** [comment]
@max-krichenbauer thanks, I'm doing the option that feeds the drawn points to Mivry with z=0 and so far seems to work. However, one question that I have is if the frame of reference is important for this case? If so what should it be?

**Comment by max-krichenbauer** [comment]
If you feed the canvas x/y coordinates (with z=0) into MiVRy, make sure that you use no transformation (position = {0,0,0}, rotation = {0,0,0,1}, or the identity matrix) as head position on `startStroke()`.
Then, the frame of reference does not matter anymore.
