### ISSUE TITLE
Error unity GestureManager scene

### ISSUE THREAD

**Issue by MrPotatoezzz** [MARUI-PlugIn/MiVRy#3]
Whenever "play" is pressed when the GestureManager scene is loaded, the following error occurs:

Mesh '': abnormal mesh bounds - most likely it has some invalid vertices (+/-inifinity or NANs) due to errors exporting.
Mesh bounds min=(-nan(ind), -nan(ind), 0.00), max=(-nan(ind), -nan(ind), 1.00). Please make sure the mesh is exported without any errors.
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by max-krichenbauer** [comment]
Thank you for the message.
However, this repository doesn't contain any meshes. 
If you have trouble with the Unity plug-in please email support@marui-plugin.com with information on which version of Unity you're using, and which mesh is causing trouble.
By the way, you don't have to run GestureManager in Unity Editor yourself. You can just download a stand-alone version from https://www.marui-plugin.com/mivry/
